# Generated by Django 3.1.1 on 2020-11-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_userfollowing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowing',
            new_name='Follow',
        ),
    ]
