# Generated by Django 3.1.1 on 2020-09-21 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, default='0.00', max_digits=50)),
                ('highest_bid', models.DecimalField(decimal_places=2, default='0.00', max_digits=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('BABY', 'Baby'), ('BEAUTY', 'Beauty'), ('BOOKS', 'Books'), ('CAMERA_PHOTO', 'Camera & Photo'), ('CLOTHING_ACCESSORIES', 'Clothing & Accessories'), ('CONSUMER_ELECTRONICS', 'Consumer Electronics'), ('GROCERY_GOURMET_FOODS', 'Grocery & Gourmet Foods'), ('HEALTH_PERSONAL_CARE', 'Health & Personal Care'), ('HOME_GARDEN', 'Home & Garden'), ('INDUSTRIAL_SCIENTIFIC', 'Industrial & Scientific'), ('LUGGAGE_TRAVEL_ACCESSORIES', 'Luggage & Travel Accessories'), ('MUSICAL_INSTRUMENTS', 'Musical Instruments'), ('OFFICE_PRODUCTS', 'Office Products'), ('OUTDOORS', 'Outdoors'), ('PERSONAL_COMPUTERS', 'Personal Computers'), ('PET_SUPPLIES', 'Pet Supplies'), ('SHOES_ANDBAGS_SUNGLASSES', 'Shoes, Handbags, & Sunglasses'), ('SOFTWARE', 'Software'), ('SPORTS', 'Sports'), ('TOOLS_HOME_IMPROVEMENT', 'Tools & Home Improvement'), ('TOYS', 'Toys'), ('VIDEOGAMES', 'Video Games'), ('OTHER', 'Other')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auction')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, default='0.00', max_digits=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auction')),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
