# Generated by Django 3.1.1 on 2020-12-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_auto_20201230_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='vital',
            field=models.CharField(choices=[('SYS_BP', 'Systolic Blood Pressure'), ('DIA_BP', 'Diastolic Blood Pressure'), ('HR', 'Heart Rate'), ('BT', 'Body Temperature'), ('RR', 'Respiratory Rate')], max_length=100, null=True),
        ),
    ]
