# Generated by Django 3.1.1 on 2020-12-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_auto_20201230_0627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vital',
        ),
    ]
