# Generated by Django 3.1.1 on 2020-12-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_delete_vital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, default='static/no-img.png', null=True, upload_to=''),
        ),
    ]
