# Generated by Django 3.1.1 on 2020-12-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0007_auto_20201230_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
